server:
  port: 8085
---
# SPRING
spring:
  main:
    bannerMode: console
  h2:
    console:
      enabled: true
      path: /console
#  datasource:
#    platform: h2
logging:
    level:
      org.grails: DEBUG
---
# GORM
dataSource:
  pooled: true
  dbCreate: create-drop
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cached: false
    region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
---
# JAVAMELODY
javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Data source names to exclude from monitoring (optional, comma-separated)
  excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers (optional, default: true)
  spring-monitoring-enabled: true
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    #storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path
    #monitoring-path: /admin/performance
---